added `nocolor` flag allowing escape sequence free logging of stdout/stderr. Updated README.md

diff --git a/cdnjs b/cdnjs
--- a/cdnjs
+++ b/cdnjs
@@ -12,6 +12,7 @@
 unset DO_INIT DO_INDEX DO_SEARCH DO_CLEAN \
 	  DO_SYNC DO_HELP DO_ADD DO_VERBOSE \
 	  HAS_CONF CONF \
+	  NO_COLOR \
 	  IS_DEV NO_DEV
 
 while [[ $1 ]]; do
@@ -29,6 +30,7 @@ while [[ $1 ]]; do
 		-s|--sync|sync|update)              DO_SYNC=1;;
 		--update|update)                    DO_SYNC=1;;
 		-a|--add|add|+)                     DO_ADD=1;;
+		--nocolor|nocolor)                  NO_COLOR=1;;
 		-h|-\?|--help|help)                 DO_HELP=1;;
 		*)                                  if [[ "$ARGS" == "" ]]; then ARGS="$1"; else ARGS="$ARGS $1"; fi;
 	esac
@@ -44,20 +46,41 @@ BLU="${SWITCH}34m"
 	
 function debug {
 	if (( DO_VERBOSE )); then
-		echo -e $YELLOW"$@"$NORMAL
+		if (( NO_COLOR )); then
+			echo -e $@
+		else
+			echo -e $YELLOW"$@"$NORMAL
+		fi
 	fi
 }
 function warn {
-	echo -e $YELLOW"$@"$NORMAL
+	if (( NO_COLOR )); then
+		echo -e $@
+	else
+		echo -e $YELLOW"$@"$NORMAL
+	fi
 }
 function info {
-	echo -e "$@"$NORMAL
+	if (( NO_COLOR )); then
+		echo -e $@
+	else
+		echo -e "$@"$NORMAL
+	fi
 }
 function green {
-	echo -e $GRN"$@"$NORMAL
+	if (( NO_COLOR )); then
+		echo -e $@
+	else
+		echo -e $GRN"$@"$NORMAL
+	fi
 }
 function error {
-	echo -e $RED"$@"$NORMAL
+	# echo -e $@ >&2
+	if (( NO_COLOR )); then
+		echo -e $@ >&2
+	else
+		echo -e $RED"$@"$NORMAL >&2
+	fi
 }
 
 list_includes () {
@@ -91,7 +114,11 @@ list_includes () {
 		debug "    extracting list of \"link\"'s and \"script\"'s"
 		local list=$(echo "$processed" | jq '.[] as $all | $all | .files[] as $list | .path as $path | $list | . |  $path + strings , $path + objects.outpath + "/" + objects.file ')
 		if (( IS_DEV )); then
-			debug "Excluding$RED min's$YELLOW from list!"
+			if (( NO_COLOR )); then
+				debug "Excluding min's from list!"
+			else
+				debug "Excluding$RED min's$YELLOW from list!"
+			fi
 			if [[ "$path_to_index" != "" ]]; then
 				local css_files=$(echo "$list" | grep -v "\.min\." | grep "\.css" | sed "s|$path_to_index||g")
 				local js_files=$(echo "$list" | grep -v "\.min\." | grep "\.js" | sed "s|$path_to_index||g")
@@ -100,7 +127,11 @@ list_includes () {
 				local js_files=$(echo "$list" | grep -v "\.min\." | grep "\.js" )
 			fi
 		elif (( NO_DEV )); then
-			debug "Listing$RED min's$YELLOW only!"
+			if (( NO_COLOR )); then
+				debug "Listing min's only!"
+			else
+				debug "Listing$RED min's$YELLOW only!"
+			fi
 			if [[ "$path_to_index" != "" ]]; then
 				local css_files=$(echo "$list" | grep "\.min\." | grep "\.css" | sed "s|$path_to_index||g")
 				local js_files=$(echo "$list" | grep "\.min\." | grep "\.js" | sed "s|$path_to_index||g")
@@ -109,8 +140,13 @@ list_includes () {
 				local js_files=$(echo "$list" | grep "\.min\." | grep "\.js" )
 			fi
 		else
-			debug "Listing$RED all$YELLOW available$RED js's$YELLOW and$RED css's$YELLOW!"
-			debug "    Use $RED--dev$YELLOW or $RED--nodev$YELLOW flags for managing minified output"
+			if (( NO_COLOR )); then
+				debug "Listing all available js's and css's!"
+				debug "    Use --dev or --nodev flags for managing minified output"
+			else
+				debug "Listing$RED all$YELLOW available$RED js's$YELLOW and$RED css's$YELLOW!"
+				debug "    Use $RED--dev$YELLOW or $RED--nodev$YELLOW flags for managing minified output"
+			fi
 			if [[ "$path_to_index" != "" ]]; then
 				local css_files=$(echo "$list" | grep "\.css" | sed "s|$path_to_index||g")
 				local js_files=$(echo "$list" | grep "\.js" | sed "s|$path_to_index||g")
@@ -137,7 +173,7 @@ init_cdnjs () {
     if [[ "$?" == "0" ]]; then
 		dir=$(dirname "${conf}")
     	if [[ ! -d "$dir" ]]; then
-    		debug "Creating directory $RED$dir"
+    		debug "Creating directory $dir"
     		mkdir -p "$dir"
 			ret=$?
     		if [[ "$ret" == "0" ]]; then
@@ -196,16 +232,21 @@ function get_resolved {
 		rm -Rf "$save_file"
 	fi
 	if (( DO_VERBOSE )); then
-		info "Fetching $RED$1$BLU to $GRN$save_dir"
-		info from $GRN$fetch_url
+		if (( NO_COLOR )); then
+			info "Fetching $1 to $save_dir"
+			info from $fetch_url
+		else
+			info "Fetching $1 to $save_dir"
+			info from $GRN$fetch_url
+		fi
 		curl "$(echo $fetch_url)" -o "$save_file" 
 	else
-		info "Fetching $RED$1$BLU"
+		info "Fetching $1$"
 		curl -s "$(echo $fetch_url)" -o "$save_file" 
 	fi
 	local ret=$?
 	if [[ "$ret" != "0" ]]; then
-		error "Could not download file $BLU$1" 
+		error "Could not download file $1" 
 	else
 		info "Success"
 	fi
@@ -279,8 +320,13 @@ sync-files () {
 			echo -e
 		fi
 		((loop++))
-		green "Repo: $BLU$repo$NORMAL"
-		green "Url: $BLU$url$NORMAL"
+		if (( NO_COLOR )); then
+			green "Repo: $repo"
+			green "Url: $url"
+		else
+			green "Repo: $BLU$repo$NORMAL"
+			green "Url: $BLU$url$NORMAL"
+		fi
 		echo -e
 		for d in $keys; do
 			lib=$d
@@ -344,16 +390,16 @@ clean () {
 	IFS=$'\r\n'
 	for d in $locations; do
 		if [[ -d "$d" ]]; then
-			echo -e $BLU'Cleaning dir '$d'.'$NORMAL
+			info 'Cleaning dir '$d'.'
 			rm -Rf "$d"
 			ret=$?
 			if (( DO_VERBOSE )) && [[ "$ret" != "0" ]]; then
-				debug "Could not$GRN delete$NORMAL$BLU$d"
+				debug "Could not delete $d"
 			else
-				debug "Successfully$GRN deleted $NORMAL$BLU$d"
+				debug "Successfully deleted $d"
 			fi
 		else
-			echo -e $RED'Dir '$d' does not exist.'$NORMAL
+			error 'Dir '$d' does not exist.'
 		fi
 	done
 	IFS=$oifs
@@ -384,6 +430,7 @@ usage (){
 	echo -e
 	echo -e "    -v, --verbose, verbose           print debug/verbose output"
 	echo -e "        --debug, debug               same as \"--verbose\""
+	echo -e "        --nocolor, nocolor           do not output in color, useful for logging stdout/stderr"
 	echo -e "    -h, -?, --help, help             print usage"
 }
 if (( ! HAS_CONF )); then
@@ -395,13 +442,21 @@ if (( DO_HELP )); then
 	exit 0
 fi
 if (( DO_INDEX )); then
-	debug "Listing script and link tags from $RED$CONF"
+	if (( NO_COLOR )); then
+		debug "Listing script and link tags from $CONF"
+	else
+		debug "Listing script and link tags from $RED$CONF"
+	fi
 	list_includes "$CONF" "$ARGS"
 	fret=$?
 	exit $fret
 fi
 if (( DO_INIT )); then
-	debug "Initializing config file $RED$CONF"
+	if (( NO_COLOR )); then
+		debug "Initializing config file $CONF"
+	else
+		debug "Initializing config file $RED$CONF"
+	fi
 	init_cdnjs "$CONF"
 	fret=$?
 	exit $fret
@@ -414,7 +469,11 @@ if (( DO_SYNC || DO_CLEAN )) && [[ ! -f "$CONF" ]]; then
 	exit 1
 fi
 if [[ "$DO_CLEAN" == "1" ]] && [[ -f "$CONF" ]]; then
-	debug "CLEANING file $RED$CONF"
+	if (( NO_COLOR )); then
+		debug "CLEANING file $CONF"
+	else
+		debug "CLEANING file $RED$CONF"
+	fi
 	clean "$CONF"
 	fret=$?
 	if [[ "$fret" != "0" ]]; then
@@ -425,13 +484,21 @@ if [[ "$DO_CLEAN" == "1" ]] && [[ -f "$CONF" ]]; then
 	fi
 fi
 if [[ "$DO_SYNC" == "1" ]] && [[ -f "$CONF" ]]; then
-	debug "SYNCING file $RED$CONF"
+	if (( NO_COLOR )); then
+		debug "SYNCING file $CONF"
+	else
+		debug "SYNCING file $RED$CONF"
+	fi
 	sync-files "$CONF"
 	exit $?
 fi
 (( DO_SEARCH  )) && unset DO_SYNC
 if (( $DO_SEARCH )); then
-	debug "SEARCHING for $RED$ARGS"
+	if (( NO_COLOR )); then
+		debug "SEARCHING for $ARGS"
+	else
+		debug "SEARCHING for $RED$ARGS"
+	fi
 	res=$(search-cdnjs "$ARGS")
 	fret=$?
 	echo $res | jq '.'
@@ -452,11 +519,19 @@ if (( $DO_ADD )); then
 		val=$(search_with_version "$search" "$version")
 		tret=$?
 		if [[ "$val" == "" ]]; then
-			error "no assets found for library: $GRN$search$RED, version: $GRN$version"
+			if (( NO_COLOR )); then
+				error "no assets found for library: $search, version: $version"
+			else
+				error "no assets found for library: $GRN$search$RED, version: $GRN$version"
+			fi
 			fret=1
 		else
 			if [[ "$tret" == "0" ]]; then
-				info "Adding $search version: $RED $(echo "$val" | jq -r --arg key "$search" '.[( $key )].version')"
+				if (( NO_COLOR )); then
+					info "Adding $search version: $(echo "$val" | jq -r --arg key "$search" '.[( $key )].version')"
+				else
+					info "Adding $search version: $RED $(echo "$val" | jq -r --arg key "$search" '.[( $key )].version')"
+				fi
 			fi
 			debug "val=$val"
 			valfin=$(jq --argjson val "$val" --arg key "$search" '. as $rr | $rr |  $rr.cdnjs.dependencies=( $rr.cdnjs.dependencies + $val ) | .' "$CONF" )
@@ -470,7 +545,11 @@ if (( $DO_ADD )); then
 			fret=1
 		else
 			if [[ "$tret" == "0" ]]; then
-				info "Adding $search version: $RED$(echo "$val" | jq -r --arg key "$search" '.[( $key )].version')"
+				if (( NO_COLOR )); then
+					info "Adding $search version: $(echo "$val" | jq -r --arg key "$search" '.[( $key )].version')"
+				else
+					info "Adding $search version: $RED$(echo "$val" | jq -r --arg key "$search" '.[( $key )].version')"
+				fi
 			fi
 			debug "val=$val"
 			valfin=$(jq --argjson val "$val" --arg key "$search" '. as $rr | $rr |  $rr.cdnjs.dependencies=( $rr.cdnjs.dependencies + $val ) | .' "$CONF")
@@ -481,7 +560,11 @@ if (( $DO_ADD )); then
 		echo $valfin | jq '.' > $tmpconf
 		fret=$?
     	if [[ "$fret" == "0" ]]; then 
-    		info "Successfully updated$GRN cdnjs$BLU config $GRN$CONF$BLU"
+			if (( NO_COLOR )); then
+    			info "Successfully updated cdnjs config $CONF"
+    		else
+    			info "Successfully updated$GRN cdnjs$BLU config $GRN$CONF$BLU"
+			fi
     		mv "$tmpconf" "$CONF"
     		fret=$?
     		if [[ "$fret" != "0" ]]; then 
