added verbose output and fixed (partially) cleaning of dirs

diff --git a/cdnjs-client b/cdnjs-client
--- a/cdnjs-client
+++ b/cdnjs-client
@@ -9,6 +9,22 @@
 #
 ##########
 	
+unset DO_SEARCH DO_CLEAN DO_SYNC DO_HELP DO_ADD DO_VERBOSE HAS_CONF CONF
+while [[ $1 ]]; do
+	case "$1" in
+		--conf)                             if [[ -f "$2" ]]; then HAS_CONF=1; CONF="$2"; shift; fi;;
+		-v|--verbose|verbose)               DO_VERBOSE=1;;
+		--debug|debug)                      DO_VERBOSE=1;;
+		-f|--search|search|--find|find)     DO_SEARCH=1;;
+		-c|--clean|clean)                   DO_CLEAN=1;;
+		-s|--sync|sync)                     DO_SYNC=1;;
+		-a|--add|add|+)                     DO_ADD=1;;
+		-h|-\?|--help|help)                 DO_HELP=1;;
+		*)                                  if [[ "$ARGS" == "" ]]; then ARGS="$1"; else ARGS="$ARGS $1"; fi;
+	esac
+	shift
+done
+
 SWITCH="\e["
 NORMAL="${SWITCH}0m"
 YELLOW="${SWITCH}33m"
@@ -16,6 +32,11 @@ RED="${SWITCH}31m"
 GRN="${SWITCH}32m"
 BLU="${SWITCH}34m"
 	
+function debug {
+	if (( DO_VERBOSE )); then
+		echo -e $YELLOW$@$NORMAL
+	fi
+}
 function warn {
 	echo -e $YELLOW$@$NORMAL
 }
@@ -66,13 +87,13 @@ function get_resolved {
 	if [[ -f "$save_file" ]]; then
 		rm -Rf "$save_file"
 	fi
-	info "Fetching $RED$1$BLUE to $GREEN$save_dir$BLUE"
-	# echo -e $GREEN
+	info "Fetching $RED$1$BLU to $GRN$save_dir$BLU"
+	# echo -e $GRN
 	wget -q -O "$save_file" $fetch_url
 	# echo -e $NORMAL
 	local ret=$?
 	if [[ "$ret" != "0" ]]; then
-		error "Could not download file $BLUE$1" 
+		error "Could not download file $BLU$1" 
 	else
 		info "Success"
 	fi
@@ -147,8 +168,8 @@ sync-files () {
 			echo -e
 		fi
 		((loop++))
-		green "Repo: $BLUE$repo$NORMAL"
-		green "Url: $BLUE$url$NORMAL"
+		green "Repo: $BLU$repo$NORMAL"
+		green "Url: $BLU$url$NORMAL"
 		echo -e
 		for d in $keys; do
 			lib=$d
@@ -201,51 +222,53 @@ sync-files () {
 	return $ret
 }
 clean () {
-	locations=$(jq -r -c '.. | select(has("relative-location"?))["relative-location"]' "$conf")
-	oifs=$IFS
+	local conf="$1"
+	local locations=$(jq -r -c '.. | select(has("relative-location"?))["relative-location"]' "$conf")
+	local oifs=$IFS
+	local ret=
+	locations=$(echo $locations | xargs -n1 | sort | uniq)
 	IFS=$'\n'
 	for d in $locations; do
 		if [[ -d "$d" ]]; then
-			echo -e $BLUE'Cleaning dir '$d'.'$NORMAL
+			echo -e $BLU'Cleaning dir '$d'.'$NORMAL
 			rm -Rf "$d"
+			ret=$?
+			if (( DO_VERBOSE )) && [[ "$ret" != "0" ]]; then
+				debug "Could not$GRN delete$NORMAL$BLU$d"
+			else
+				debug "Successfully$GRN deleted $NORMAL$BLU$d"
+			fi
 		else
 			echo -e $RED'Dir '$d' does not exist.'$NORMAL
 		fi
 	done
 	IFS=$oifs
-	return $?
+	return $ret
 }
 
 
-unset DO_SEARCH DO_CLEAN DO_SYNC DO_HELP DO_ADD HAS_CONF CONF
-while [[ $1 ]]; do
-	case "$1" in
-		--conf)                             if [[ -f "$2" ]]; then HAS_CONF=1; CONF="$2"; shift; fi;;
-		-f|--search|search|--find|find)     DO_SEARCH=1;;
-		-c|--clean|clean)                   DO_CLEAN=1;;
-		-s|--sync|sync)                     DO_SYNC=1;;
-		-a|--add|add|+)                     DO_ADD=1;;
-		-h|-\?|--help|help)                  DO_HELP=1;;
-		*)                                  if [[ "$ARGS" == "" ]]; then ARGS="$1"; else ARGS="$ARGS $1"; fi;
-	esac
-	shift
-done
 
 usage (){
 	echo -e "Usage: $(basename ${BASH_SOURCE[0]}) [OPTIONS] [ARGS]:"
 	echo -e
+	echo -e "    Options:"
 	echo -e "    --conf [CONFIG FILE]            use a custom config file"
-	echo -e "    --search, search [ARGS]         perform query on api.cdnjs.com"
-	echo -e "    -f, --find, find [ARGS]         same as \"--search [ARGS]\""
+	echo -e
+	echo -e "    -f, --find, find [ARGS]         perform query on api.cdnjs.com"
+	echo -e "        --search, search [ARGS]     same as \"--search [ARGS]\""
+	echo -e
 	echo -e "    -c, --clean, clean [ARGS]       clean configured relative-location"
 	echo -e "    -s, --sync, sync [ARGS]         syncronize to configured relative-locations"
-	echo -e "    -a, + [LIB[+VERSION]] [GROUP]   add library with optional version to optional group"
-	echo -e "    --add, add                      same as \"--add\""
+	echo -e "    -a, + [LIB[+VERSION]] [GROUP]   add library with optional version to optional"
+	echo -e "        --add, add                   group"
+	echo -e
+	echo -e "    -v, --verbose, verbose          print debug/verbose output"
+	echo -e "        --debug, debug              same as \"--verbose\""
 	echo -e "    -h, -?, --help, help            print usage"
 }
 if (( ! HAS_CONF )); then
 	CONF='.cdnjs'
-	info using default config: $CONF
+	debug "using default config: $CONF"
 fi
 if (( DO_HELP )); then
 	usage
@@ -254,27 +277,29 @@ fi
 
 (( ! DO_SYNC && ! DO_SEARCH && ! DO_CLEAN  && ! DO_ADD )) && DO_SYNC=1
 (( DO_SYNC || DO_CLEAN )) && unset DO_SEARCH
-if (( DO_SYNC || DO_CLEAN )) && [[ ! -f "$ARGS" ]]; then
+if (( DO_SYNC || DO_CLEAN )) && [[ ! -f "$CONF" ]]; then
 	error "A cdnjs-client configuration file is required!"
 	exit 1
 fi
 if [[ "$DO_CLEAN" == "1" ]] && [[ -f "$CONF" ]]; then
-	info "CLEANING file $CONF"
+	debug "CLEANING file $RED$CONF"
 	clean "$CONF"
 	fret=$?
 	if [[ "$fret" != "0" ]]; then
 		error "Cleaning was not successful"
 		exit $fret
+	else
+		debug "Successfully cleaned 'relative-location's"
 	fi
 fi
 if [[ "$DO_SYNC" == "1" ]] && [[ -f "$CONF" ]]; then
-	info "SYNCING file $CONF"
+	debug "SYNCING file $RED$CONF"
 	sync-files "$CONF"
 	exit $?
 fi
 (( DO_SEARCH  )) && unset DO_SYNC
 if (( $DO_SEARCH )); then
-	info "SEARCHING for $ARGS"
+	debug "SEARCHING for $RED$ARGS"
 	res=$(search-cdnjs "$ARGS")
 	fret=$?
 	echo $res | jq '.'
